name: Build & Publish docker image for DAGMC-CI

on:
  # allows us to run workflows manually
  workflow_dispatch:
  push:
    paths:
      - 'CI/Dockerfile'
      - '.github/workflows/docker_publish.yml'

jobs:
  build-dependency-and-test-img:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ubuntu_version : [
          20.04,
          22.04,
          ]
        compiler : [
          gcc,
          clang,
          ]
        hdf5_version : [
         1.10.4,
        ]
        moab_version : [
         5.3.0,
        ]
        double_down_version : [
          1.1.0,
        ]
        geant4_version : [
          10.7.4,
          11.1.2
        ]

    name: Installing Dependencies, Building DAGMC and running tests
    steps:
      - name: default environment
        run: |
          echo "tag-latest-on-default=false" >> "$GITHUB_ENV"

      - name: condition on trigger parameters
        if: ${{ github.repository_owner == 'svalinn' && github.ref == 'refs/heads/develop' }}
        run: |
          echo "tag-latest-on-default=true" >> "$GITHUB_ENV"

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Installing Dependencies in Docker image
        uses: firehed/multistage-docker-build-action@v1
        with:
          repository: ghcr.io/${{ github.repository_owner }}/dagmc-ci-ubuntu-${{ matrix.ubuntu_version }}-${{ matrix.compiler}}-geant4_${{ matrix.geant4_version }}-hdf5_${{ matrix.hdf5_version}}-moab_${{ matrix.moab_version }}
          stages: base, external_deps, hdf5, moab, dagmc
          server-stage: dagmc_test
          quiet: false
          parallel: true
          tag-latest-on-default: ${{ env.tag-latest-on-default }}
          dockerfile: CI/Dockerfile
          build-args: DOUBLE_DOWN_VERSION=${{ matrix.double_down_version}}, Geant4_VERSION=${{ matrix.geant4_version }}, COMPILER=${{ matrix.compiler }}, UBUNTU_VERSION=${{ matrix.ubuntu_version }}, HDF5_VERSION=${{ matrix.hdf5_version }}, MOAB_VERSION=${{ matrix.moab_version }}


  push_stable_ci_img:
    needs: [build-dependency-and-test-img]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ubuntu_version : [
          20.04,
          22.04,
          ]
        compiler : [
          gcc,
          clang,
          ]
        hdf5_version : [
          1.10.4,
        ]
        moab_version : [
          5.3.0,
        ]
        double_down_version : [
          1.1.0,
        ]
        geant4_version : [
          10.7.4,
          11.1.2
        ]

    name: Pushing final images
    steps:       
      - name: Log in to the Container registry
        if: ${{ github.repository_owner == 'svalinn' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Store image name
        if: ${{ github.repository_owner == 'svalinn' }}
        run: |
          echo "image_base_tag=ghcr.io/${{ github.repository_owner }}/dagmc-ci-ubuntu-${{ matrix.ubuntu_version }}-${{ matrix.compiler }}-geant4_${{ matrix.geant4_version }}-hdf5_${{ matrix.hdf5_version }}-moab_${{ matrix.moab_version }}" >> "$GITHUB_ENV"

      - name: Push Image as latest img
        if: ${{ github.repository_owner == 'svalinn' && github.ref == 'refs/heads/develop' }}
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: ${{ env.image_base_tag }}/dagmc:latest
          dst: ${{ env.image_base_tag }}:latest

      - name: Push Image as latest img
        if: ${{ github.repository_owner == 'svalinn' && github.ref == 'refs/heads/develop' }}
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: ${{ env.image_base_tag }}:latest
          dst: ${{ env.image_base_tag }}:stable
