on:
  push:
    branches: ['gh_actions_and_ghcr_for_docker']  # todo replace with main once we know this is working

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    env:
      hdf5_versions: 1.10.4
      hdf5_build_dir: hdf5_build_dir

    strategy:
      matrix:
       ubuntu_versions : [
          16.04,
          18.04,
          ]
       compiler : [
          gcc,
          clang,
          ]
       hdf5_versions : [
         1.10.4,
       ]
       moab_versions : [
         9c96d17,
         develop,
         master,
       ]




    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v7.1
        id: verify-changed-files
        with:
          files: |
              CI

      - name: Build and push Dockerfile_0_base
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: docker/build-push-action@v2
        with:
          file: CI/Dockerfile_0_base
          context: .
          push: true
          build-args: |
            UBUNTU_VERSION=${{ matrix.ubuntu_versions }}
          tags: ghcr.io/svalinn/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}

      - name: Build and push Dockerfile_1_external_deps
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: docker/build-push-action@v2
        with:
          file: CI/Dockerfile_1_external_deps
          context: .
          push: true
          build-args: |
            UBUNTU_VERSION=${{ matrix.ubuntu_versions }}
            COMPILER=${{ matrix.compiler }}
          tags: ghcr.io/svalinn/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-${{ matrix.compiler}}-ext

      - name: Build and push Dockerfile_2_hdf5
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: docker/build-push-action@v2
        with:
          file: CI/Dockerfile_2_hdf5
          context: .
          push: true
          build-args: |
            UBUNTU_VERSION=${{ matrix.ubuntu_versions }}
            COMPILER=${{ matrix.compiler }}
            HDF5=${{ matrix.hdf5_versions }}
          tags: ghcr.io/svalinn/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-${{ matrix.compiler}}-ext-hdf5_${{ matrix.hdf5_versions}}

      - name: Build and push Dockerfile_3_moab
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: docker/build-push-action@v2
        with:
          file: CI/Dockerfile_3_moab
          context: .
          push: true
          build-args: |
            UBUNTU_VERSION=${{ matrix.ubuntu_versions }}
            COMPILER=${{ matrix.compiler }}
            HDF5=${{ matrix.hdf5_versions }}
            MOAB=${{ matrix.moab_versions }}
          tags: ghcr.io/svalinn/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-${{ matrix.compiler}}-ext-hdf5_${{ matrix.hdf5_versions}}-moab_${{ matrix.moab_versions }}

      - name: Build and push Dockerfile_1_housekeeping
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: docker/build-push-action@v2
        with:
          file: CI/Dockerfile_1_housekeeping
          context: .
          push: true
          build-args: |
            UBUNTU_VERSION=${{ matrix.ubuntu_versions }}
          tags: ghcr.io/svalinn/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-housekeeping
      